// <auto-generated />
using System;
using DatabaseTask.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DatabaseTask.Data.Migrations
{
    [DbContext(typeof(DatabaseTaskDbContext))]
    [Migration("20260924103800_Prison")]
    partial class Prison
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("DatabaseTask.Core.Domain.Block", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Number")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<Guid>("PrisonId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("SecurityLevel")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("Id");

                    b.HasIndex("PrisonId");

                    b.ToTable("Blocks");
                });

            modelBuilder.Entity("DatabaseTask.Core.Domain.Cell", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("BlockId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Floor")
                        .HasColumnType("int");

                    b.Property<int>("MaxCapacity")
                        .HasColumnType("int");

                    b.Property<string>("Number")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.HasKey("Id");

                    b.HasIndex("BlockId");

                    b.ToTable("Cells");
                });

            modelBuilder.Entity("DatabaseTask.Core.Domain.CellAssignment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CellId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("EndDate")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("PrisonerId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("CellId");

                    b.HasIndex("PrisonerId");

                    b.ToTable("CellAssignments");
                });

            modelBuilder.Entity("DatabaseTask.Core.Domain.Crime", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("Severity")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Crimes");
                });

            modelBuilder.Entity("DatabaseTask.Core.Domain.Guard", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("EmployeeNumber")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Position")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("Guards");
                });

            modelBuilder.Entity("DatabaseTask.Core.Domain.GuardShift", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("GuardId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ShiftId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("GuardId");

                    b.HasIndex("ShiftId");

                    b.ToTable("GuardShifts");
                });

            modelBuilder.Entity("DatabaseTask.Core.Domain.Prison", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("MaxCapacity")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("Prisons");
                });

            modelBuilder.Entity("DatabaseTask.Core.Domain.Prisoner", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("ArrivalDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DateOfBirth")
                        .HasColumnType("datetime2");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("PersonalCode")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Prisoners");
                });

            modelBuilder.Entity("DatabaseTask.Core.Domain.PrisonerCrime", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CrimeId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("PrisonerId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("CrimeId");

                    b.HasIndex("PrisonerId");

                    b.ToTable("PrisonerCrimes");
                });

            modelBuilder.Entity("DatabaseTask.Core.Domain.Sentence", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CrimeId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("PrisonerId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("SentenceType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("CrimeId");

                    b.HasIndex("PrisonerId");

                    b.ToTable("Sentences");
                });

            modelBuilder.Entity("DatabaseTask.Core.Domain.Shift", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<TimeSpan>("EndTime")
                        .HasColumnType("time");

                    b.Property<TimeSpan>("StartTime")
                        .HasColumnType("time");

                    b.HasKey("Id");

                    b.ToTable("Shifts");
                });

            modelBuilder.Entity("DatabaseTask.Core.Domain.Visit", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<TimeSpan>("EndTime")
                        .HasColumnType("time");

                    b.Property<Guid>("PrisonerId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<TimeSpan>("StartTime")
                        .HasColumnType("time");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<Guid>("VisitorId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("PrisonerId");

                    b.HasIndex("VisitorId");

                    b.ToTable("Visits");
                });

            modelBuilder.Entity("DatabaseTask.Core.Domain.Visitor", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("PersonalCode")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Relationship")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("Visitors");
                });

            modelBuilder.Entity("DatabaseTask.Core.Domain.Block", b =>
                {
                    b.HasOne("DatabaseTask.Core.Domain.Prison", "Prison")
                        .WithMany("Blocks")
                        .HasForeignKey("PrisonId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Prison");
                });

            modelBuilder.Entity("DatabaseTask.Core.Domain.Cell", b =>
                {
                    b.HasOne("DatabaseTask.Core.Domain.Block", "Block")
                        .WithMany("Cells")
                        .HasForeignKey("BlockId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Block");
                });

            modelBuilder.Entity("DatabaseTask.Core.Domain.CellAssignment", b =>
                {
                    b.HasOne("DatabaseTask.Core.Domain.Cell", "Cell")
                        .WithMany("CellAssignments")
                        .HasForeignKey("CellId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("DatabaseTask.Core.Domain.Prisoner", "Prisoner")
                        .WithMany("CellAssignments")
                        .HasForeignKey("PrisonerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Cell");

                    b.Navigation("Prisoner");
                });

            modelBuilder.Entity("DatabaseTask.Core.Domain.GuardShift", b =>
                {
                    b.HasOne("DatabaseTask.Core.Domain.Guard", "Guard")
                        .WithMany("GuardShifts")
                        .HasForeignKey("GuardId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("DatabaseTask.Core.Domain.Shift", "Shift")
                        .WithMany("GuardShifts")
                        .HasForeignKey("ShiftId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Guard");

                    b.Navigation("Shift");
                });

            modelBuilder.Entity("DatabaseTask.Core.Domain.PrisonerCrime", b =>
                {
                    b.HasOne("DatabaseTask.Core.Domain.Crime", "Crime")
                        .WithMany("PrisonerCrimes")
                        .HasForeignKey("CrimeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("DatabaseTask.Core.Domain.Prisoner", "Prisoner")
                        .WithMany("PrisonerCrimes")
                        .HasForeignKey("PrisonerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Crime");

                    b.Navigation("Prisoner");
                });

            modelBuilder.Entity("DatabaseTask.Core.Domain.Sentence", b =>
                {
                    b.HasOne("DatabaseTask.Core.Domain.Crime", "Crime")
                        .WithMany("Sentences")
                        .HasForeignKey("CrimeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("DatabaseTask.Core.Domain.Prisoner", "Prisoner")
                        .WithMany("Sentences")
                        .HasForeignKey("PrisonerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Crime");

                    b.Navigation("Prisoner");
                });

            modelBuilder.Entity("DatabaseTask.Core.Domain.Visit", b =>
                {
                    b.HasOne("DatabaseTask.Core.Domain.Prisoner", "Prisoner")
                        .WithMany("Visits")
                        .HasForeignKey("PrisonerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("DatabaseTask.Core.Domain.Visitor", "Visitor")
                        .WithMany("Visits")
                        .HasForeignKey("VisitorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Prisoner");

                    b.Navigation("Visitor");
                });

            modelBuilder.Entity("DatabaseTask.Core.Domain.Block", b =>
                {
                    b.Navigation("Cells");
                });

            modelBuilder.Entity("DatabaseTask.Core.Domain.Cell", b =>
                {
                    b.Navigation("CellAssignments");
                });

            modelBuilder.Entity("DatabaseTask.Core.Domain.Crime", b =>
                {
                    b.Navigation("PrisonerCrimes");

                    b.Navigation("Sentences");
                });

            modelBuilder.Entity("DatabaseTask.Core.Domain.Guard", b =>
                {
                    b.Navigation("GuardShifts");
                });

            modelBuilder.Entity("DatabaseTask.Core.Domain.Prison", b =>
                {
                    b.Navigation("Blocks");
                });

            modelBuilder.Entity("DatabaseTask.Core.Domain.Prisoner", b =>
                {
                    b.Navigation("CellAssignments");

                    b.Navigation("PrisonerCrimes");

                    b.Navigation("Sentences");

                    b.Navigation("Visits");
                });

            modelBuilder.Entity("DatabaseTask.Core.Domain.Shift", b =>
                {
                    b.Navigation("GuardShifts");
                });

            modelBuilder.Entity("DatabaseTask.Core.Domain.Visitor", b =>
                {
                    b.Navigation("Visits");
                });
#pragma warning restore 612, 618
        }
    }
}
